# Ragnar TTRPG Platform - Cloud Infrastructure
# Docker Compose configuration for production Nextcloud deployment
# 
# This configuration implements a secure, scalable cloud storage solution
# with automated SSL certificate management and reverse proxy setup.
# 
# Architecture:
# - Nginx: Reverse proxy with SSL termination
# - Certbot: Automated Let's Encrypt certificate management
# - Nextcloud: Cloud storage and collaboration platform
# 
# Author: Stefano Sciacovelli (https://github.com/M04ph3u2)
# Version: 1.0.0
# Last Updated: 2025

services:

  # ============================================================================
  # NGINX REVERSE PROXY SERVICE
  # ============================================================================
  # 
  # Nginx serves as the reverse proxy and SSL termination point.
  # It handles:
  # - HTTP to HTTPS redirects
  # - SSL certificate management
  # - Request routing to Nextcloud
  # - ACME challenge handling for Let's Encrypt
  nginx:
    container_name: nginx
    restart: always                           # Always restart on failure
    image: nginx:1.24.0                      # Specific version for stability
    ports:
      - "80:80"                              # HTTP port for redirects and ACME challenges
      - "443:443"                            # HTTPS port for secure traffic
    volumes:
      - ./web:/etc/nginx/                    # Custom nginx configuration
      - ../data/certbot/conf:/etc/letsencrypt # SSL certificates from Let's Encrypt
      - ../data/certbot/www:/var/www/certbot  # ACME challenge directory
    deploy:
      resources:
        limits:
          cpus: '0.10'                       # Max 10% CPU usage
          memory: 128M                       # Max 128MB RAM
        reservations:
          cpus: '0.05'                       # Reserve 5% CPU
          memory: 64M                        # Reserve 64MB RAM
  
  # ============================================================================
  # CERTBOT SSL CERTIFICATE MANAGEMENT
  # ============================================================================
  # 
  # Certbot handles automated SSL certificate generation and renewal
  # using the Let's Encrypt ACME protocol. It works in coordination
  # with Nginx to handle the ACME challenge verification process.
  certbot:
    container_name: certbot
    image: certbot/certbot:v2.8.0            # Specific version for stability
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt # Certificate storage
      - ../data/certbot/www:/var/www/certbot  # ACME challenge directory
    # Certificate generation command with security best practices:
    # - webroot: Use webroot authentication method
    # - rsa-key-size 4096: High security key size
    # - agree-tos: Agree to Let's Encrypt Terms of Service
    # - force-renewal: Force renewal even if not due (for initial setup)
    command: certonly --webroot -w /var/www/certbot --email "$CERTBOT_EMAIL" -d "cloud.$DOMAIN" --rsa-key-size 4096 --agree-tos --no-eff-email --force-renewal
    depends_on:
      - nginx                                 # Ensure nginx is running for ACME challenges
    
  # ============================================================================
  # NEXTCLOUD CLOUD STORAGE SERVICE
  # ============================================================================
  # 
  # Nextcloud provides the core cloud storage functionality including:
  # - File sharing and synchronization
  # - Collaborative editing
  # - User management
  # - Integration with external storage
  nextcloud:
    container_name: nextcloud
    image: nextcloud:27.1.9                  # LTS version for stability
    restart: always                          # Always restart on failure
    volumes:
      # Custom Apache configuration for optimized performance
      - ../data/nextcloud/nextcloud.conf:/etc/apache2/conf-enabled/nextcloud.conf
      # Persistent data storage for user files and application data
      - ../data/nextcloud:/var/www/html
      # SSL certificates for internal HTTPS handling
      - ../data/certbot/conf:/etc/letsencrypt
      # ACME challenge directory (if needed for internal verification)
      - ../data/certbot/www:/var/www/certbot
    environment:
      # Domain configuration for proper URL handling behind reverse proxy
      - OVERWRITEHOST=cloud.$DOMAIN          # Set the correct hostname
      - OVERWRITECLIURL=http://cloud.$DOMAIN # CLI URL for background jobs
      - OVERWRITEPROTOCOL=https              # Force HTTPS protocol
      - VIRTUAL_HOST=cloud.$DOMAIN           # Virtual host for proxy
      
      # External database connection configuration
      # Using external MySQL/MariaDB for better performance and scalability
      - MYSQL_HOST=$MYSQL_HOST               # Database server hostname
      - MYSQL_DATABASE=$MYSQL_DATABASE       # Database name
      - MYSQL_USER=$MYSQL_USER               # Database username
      - MYSQL_PASSWORD=$MYSQL_PASSWORD       # Database password (use secure password)
      
      # Nextcloud administrator account configuration
      # These credentials are used for the initial admin user creation
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER         # Admin username
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD # Admin password (use strong password)
      
      # PHP configuration for handling large files and complex operations
      - PHP_MEMORY_LIMIT=1024M               # Increased memory limit for file operations
    deploy:
      resources:
        limits:
          cpus: '0.65'                       # Max 65% CPU usage for file operations
          memory: 650M                       # Max 650MB RAM for file processing
        reservations:
          cpus: '0.10'                       # Reserve 10% CPU for basic operations
          memory: 250M                       # Reserve 250MB RAM for core functionality

# ============================================================================
# DEPLOYMENT NOTES
# ============================================================================
# 
# Environment Variables Required:
# - DOMAIN: Your domain name (e.g., example.com)
# - CERTBOT_EMAIL: Email for Let's Encrypt registration
# - MYSQL_HOST: External MySQL/MariaDB server hostname
# - MYSQL_DATABASE: Database name for Nextcloud
# - MYSQL_USER: Database username
# - MYSQL_PASSWORD: Database password
# - NEXTCLOUD_ADMIN_USER: Initial admin username
# - NEXTCLOUD_ADMIN_PASSWORD: Initial admin password
# 
# Data Persistence:
# - ../data/nextcloud: Nextcloud application and user data
# - ../data/certbot: SSL certificates and configuration
# 
# Security Considerations:
# - All containers run with resource limits to prevent DoS
# - SSL certificates use 4096-bit RSA keys
# - External database reduces attack surface
# - Regular security updates should be applied to container images
# 
# Maintenance:
# - SSL certificates auto-renew via Let's Encrypt
# - Regular backups of ../data directory recommended
# - Monitor container logs for security events
# - Update container images regularly for security patches