version: "2"

services:

  #Web services
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.24.0
    mem_limit: 150m
    mem_reservation: 128M
    cpus: 0.15
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/etc/nginx/
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:v2.8.0
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email "$CERTBOT_EMAIL" -d "cloud.$DOMAIN" --rsa-key-size 4096 --agree-tos --no-eff-email --force-renewal
    depends_on:
      - nginx
    
  #Cloud service
  nextcloud:
    container_name: nextcloud
    image: nextcloud:27.1.9
    mem_limit: 600m
    mem_reservation: 300M
    cpus: 0.4
    restart: always
    volumes:
      - ../data/nextcloud:/var/www/html
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    environment:
      - OVERWRITEHOST=cloud.$DOMAIN
      - OVERWRITECLIURL=http://cloud.$DOMAIN
      - OVERWRITEPROTOCOL=https
      - VIRTUAL_HOST=cloud.$DOMAIN
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD