name: Deploy Trigger

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - run: |
        curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.CONTENTS_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository_owner }}/${{ secrets.SECRET_REPO_NAME }}/dispatches \
              -d "{\"event_type\": \"jugglehive-deploy\", \"client_payload\": {\"service\": \"cloud\", \"server\": \"${{ secrets.HOST }}\", \"unit\": false, \"integration\": true}}"