# ===============================================================================
# Ragnar TTRPG Platform - SSL Certificate Kickstart Configuration
# ===============================================================================
# This configuration is used for initial SSL certificate generation when
# setting up a new deployment. It provides a minimal nginx setup that allows
# Let's Encrypt to perform domain validation via HTTP-01 challenges.
# 
# Author: Stefano Sciacovelli (https://github.com/M04ph3u2)
# DevOps Infrastructure Implementation
# ===============================================================================

services:

  # ============================================================================
  # Initial SSL Setup - Nginx Container
  # ============================================================================
  # Minimal nginx configuration for certificate generation:
  # - Serves only HTTP (port 80) for ACME challenges
  # - No SSL configuration (certificates don't exist yet)
  # - Lightweight setup for quick certificate generation
  # ============================================================================
  nginx:
    container_name: ks_nginx             # Kickstart-specific container name
    restart: unless-stopped              # Restart policy for certificate generation
    image: nginx:1.24.0                  # Same nginx version as production
    ports:
      - "80:80"                          # HTTP only for ACME challenges
      - "443:443"                        # HTTPS port reserved for future use
    volumes:
      # Minimal nginx configuration for certificate generation
      - ./web:/etc/nginx/
      # Certificate storage directory (empty initially, populated by certbot)
      - ../../data/certbot/conf:/etc/letsencrypt
      # ACME challenge directory for domain verification
      - ../../data/certbot/www:/var/www/certbot

  # ============================================================================
  # Let's Encrypt Certificate Generation (Kickstart)
  # ============================================================================
  # One-time certificate generation service:
  # - Performs initial domain validation
  # - Creates SSL certificates for production use
  # - Runs once then exits (no renewal in kickstart mode)
  # ============================================================================
  certbot:
    container_name: ks_certbot           # Kickstart-specific certbot container
    image: certbot/certbot:v2.8.0        # Same certbot version as production
    volumes:
      # Certificate output directory (shared with nginx)
      - ../../data/certbot/conf:/etc/letsencrypt
      # ACME challenge serving directory
      - ../../data/certbot/www:/var/www/certbot
    # Certificate generation command for initial setup:
    # This creates certificates that will be used by the production configuration
    command: certonly --webroot -w /var/www/certbot --email "$CERTBOT_EMAIL" -d "$DOMAIN" -d "www.$DOMAIN" --rsa-key-size 4096 --agree-tos --no-eff-email --force-renewal
    depends_on:
      - nginx                            # Ensure nginx is ready to serve challenges