name: stopvm

on:
  schedule:
    - cron: '30 05 * * *'

jobs:
  
  backup:
    runs-on: ubuntu-latest

    steps:

      - name: Nextcloud Backup
        uses: appleboy/ssh-action@master
        with:
          host: cloud.${{ secrets.DOMAIN }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script:
            sudo cd /root/docker
            sudo docker compose down
            sudo cd /root/data
            sudo zip -r ./nextcloud-backup.zip ./nextcloud
            sudo az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-$(date +"%Y-%m-%d").zip \
            --file nextcloud-backup.zip \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY}} \
            --overwrite 1> /dev/null
            sudo rm -rf ./nextcloud-backup.zip
            mysqldump -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} --password=${{secrets. MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} > nextcloud-db-backup.sql
            sudo az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-db-$(date +"%Y-%m-%d").sql \
            --file nextcloud-db-backup.sql \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY}} \
            --overwrite 1> /dev/null
            sudo rm -rf ./nextcloud-db-backup.sql
            sudo cd /root/docker
            sudo docker compose up -d

  cloud-ops:
    needs: backup
    runs-on: ubuntu-latest

    steps: 

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Old Backup Cleanup
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --source backup \
            --name nextcloud-$(date -d "-4 days" +"%Y-%m-%d").zip \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} > /dev/null
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --source backup \
            --name nextcloud-$(date -d "-5 days" +"%Y-%m-%d").zip \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} > /dev/null
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --source backup \
            --name nextcloud-db-$(date -d "-4 days" +"%Y-%m-%d").sql \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} > /dev/null
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --source backup \
            --name nextcloud-db-$(date -d "-5 days" +"%Y-%m-%d").sql \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} > /dev/null

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az vm stop --resource-group jugglehive --name jugglehive-cloud
            az vm deallocate --resource-group jugglehive --name jugglehive-cloud
            az vm stop --resource-group jugglehive --name jugglehive-webapp
            az vm deallocate --resource-group jugglehive --name jugglehive-webapp