name: stopvm

on:
  schedule:
    - cron: '30 21 * * *'

jobs:
  
  backup:
    runs-on: ubuntu-latest

    steps:

      - name: Nextcloud Backup
        uses: appleboy/ssh-action@master
        with:
          host: cloud.${{ secrets.DOMAIN }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /root/docker
            sudo docker compose down
            cd /root/data
            sudo chown -R ${{ secrets.SERVER_USERNAME }}:${{ secrets.SERVER_USERNAME }} ./nextcloud
            zip -r ./nextcloud-backup.zip ./nextcloud
            az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-$(date +"%Y-%m-%d").zip \
            --file nextcloud-backup.zip \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY}} \
            --overwrite 1> /dev/null
            sudo chown -R www-data:www-data ./nextcloud
            rm -rf ./nextcloud-backup.zip
            mysqldump -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} --password=${{secrets. MYSQL_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} > nextcloud-db-backup.sql
            az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-db-$(date +"%Y-%m-%d").sql \
            --file nextcloud-db-backup.sql \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY}} \
            --overwrite 1> /dev/null
            rm -rf ./nextcloud-db-backup.sql
        
      - name: Old Backup Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: cloud.${{ secrets.DOMAIN }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-$(date +"%Y-%m-%d" -d "-4 days").zip \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} || true
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-$(date +"%Y-%m-%d" -d "-5 days").zip \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} || true
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-db-$(date +"%Y-%m-%d" -d "-4 days").sql \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} || true
            az storage blob delete \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --container-name backup \
            --name nextcloud-db-$(date +"%Y-%m-%d" -d "-5 days").sql \
            --sas-token ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} || true

  stopvm:
    needs: backup
    runs-on: ubuntu-latest

    steps: 

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az vm stop --resource-group jugglehive --name jugglehive-cloud
            az vm deallocate --resource-group jugglehive --name jugglehive-cloud
            az vm stop --resource-group jugglehive --name jugglehive-webapp
            az vm deallocate --resource-group jugglehive --name jugglehive-webapp